export const TASKS_LOADING = 'TASKS_LOADING';
export const SET_TASKS_LOADING = 'SET_TASKS_LOADING';

export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const GET_TASK_DETAIL_SUCCESS = 'GET_TASK_DETAIL_SUCCESS';
export const GET_TASK_DETAIL_ERROR = 'GET_TASK_DETAIL_ERROR';

export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';